### ISSUE TITLE
Failed assertion: line 438 pos 16

### ISSUE THREAD

**Issue by mi6crazyheart** [renefloor/flutter_cached_network_image#42] opened 2018-04-28 12:12 UTC
Hi, I'm using this plugin in one of my app. What I've noticed is whenever I'm opening my first time my app I'm getting following error in my Android Studio.

`I/flutter (18321): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18321): The following assertion was thrown building MyTabs(dirty, state: MyTabsState#1bcf5(ticker
I/flutter (18321): inactive)):
I/flutter (18321): 'package:cached_network_image/cached_network_image.dart': Failed assertion: line 438 pos 16: 'url !=
I/flutter (18321): null': is not true.
I/flutter (18321): 
I/flutter (18321): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18321): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18321): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18321):   https://github.com/flutter/flutter/issues/new
I/flutter (18321): 
I/flutter (18321): When the exception was thrown, this was the stack:
I/flutter (18321): #2      new CachedNetworkImageProvider (package:cached_network_image/cached_network_image.dart)
I/flutter (18321): #3      MyTabsState.build (file:///Users/sureshkumarmajhi/AndroidStudioProjects/bhramaan/lib/base.dart:97:44)
I/flutter (18321): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3722:27)
I/flutter (18321): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter (18321): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter (18321): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter (18321): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter (18321): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter (18321): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter (18321): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter (18321): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (18321): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter (18321): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (18321): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (18321): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (18321): #101    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4429:32)
I/flutter (18321): #102    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
I/flutter (18321): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #104    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (18321): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (18321): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #112    ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
I/flutter (18321): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter (18321): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (18321): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter (18321): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter (18321): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter (18321): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter (18321): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (18321): #126    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
I/flutter (18321): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (18321): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (18321): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (18321): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (18321): #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (18321): #132    _invoke (dart:ui/hooks.dart:120:13)
I/flutter (18321): #133    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (18321): (elided 2 frames from class _AssertionError)
`

My Flutter doctor summery is -

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.3.3-pre.12, on Mac OS X 10.13.4 17E199, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)

• No issues found!

Sample code from my "Drawer Widget" 

    drawer: new Drawer(
      child: new ListView(
        children: <Widget>[
          new UserAccountsDrawerHeader(
            accountName: new Text("${userDetails['name']??''}"),
            accountEmail: new Text("${userDetails['email']??''}"),
            currentAccountPicture: new GestureDetector(
              child: new CircleAvatar(
                backgroundImage: new CachedNetworkImageProvider(this.profileImgPath),
              ),
            ),
            decoration: new BoxDecoration(
                image: new DecorationImage(
                  fit: BoxFit.fill,
                  image: new AssetImage('images/user-background.png'),
                )
            ),
          ),
          new ListTile(
            title: new Text("Profile"),
            trailing: new Icon(Icons.account_circle),
            onTap: (){
              Navigator.of(context).pop();
              Navigator.of(context).pushNamed('/UserProfile');
            },
          ),
          new Divider(),
          new ListTile(
              title: new Text("Logout"),
              trailing: new Icon(Icons.cancel),
              onTap: () {
                clearUserDetails();
                Navigator.of(context).pop();
                Navigator.of(context).push(new MaterialPageRoute(builder: (BuildContext context) => new LandingPage()));
              }
          ),
        ],
      ),
    ),

I've no clue what's happening inside. Maybe big bros can fig. out. :)

**Comment by renefloor** [comment] 2018-04-28 14:37
Looks like the problem is that `this.profileImgPath` is nul. From this code I can't see how you load or set that path, but perhaps the user info still has to load? I would add a null check around it and use an asset image if the url is null.

For now I'll close this issue as it doesn't look like an issue with the library.

**Closed by renefloor** 2018-04-28 14:37 UTC

**Comment by mi6crazyheart** [comment] 2018-04-29 04:40
@renefloor You are right that was for that passing ```null```. After swicthing to following ```backgroundImage: (this.profileImgPath == null) ? new AssetImage('images/user-avatar.png') : new CachedNetworkImageProvider(this.profileImgPath)``` it's fixed. Thanks for having a look.
