### ISSUE TITLE
Invalid radix-16 number error

### ISSUE THREAD

**Issue by alexJetski** [renefloor/flutter_cached_network_image#87] opened 2018-10-20 21:53 UTC
To reproduce 

pubspec

name: another_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:                 ^0.12.0 
  cached_network_image: ^0.5.0
___________________________
main.dart

import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'CachedNetworkImage Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'CachedNetworkImage'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;
  MyHomePage({this.title});

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(title),
      ),
      body:
      new SingleChildScrollView(child:
      new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[

            _sizedContainer(
              new Image(
                image: new CachedNetworkImageProvider("http://via.placeholder.com/350x150"),
              ),
            ),
          ],
        ),
      ),
      ),
    );
  }

  Widget _sizedContainer(Widget child) {
    return new SizedBox(
      width: 300.0,
      height: 150.0,
      child: new Center(
        child: child,
      ),
    );
  }
}
_________________________
Flutter Version

Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (4 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044
__________________________
Error

Xcode build done.                                           10.0s
Installing and launching...                                 20.0s
Syncing files to device Ecto...
flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following FormatException was thrown resolving an image codec:
flutter: Invalid radix-16 number
flutter: ffffffff936a1cd8
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:130:5)
flutter: #1      int._parse (dart:core/runtime/libintegers_patch.dart:104:14)
flutter: #2      int.parse (dart:core/runtime/libintegers_patch.dart:61:12)
flutter: #3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:396:22)
flutter: #4      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:365:12)
flutter: #5      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:432:39)
flutter: #6      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:365:12)
flutter: #7      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:546:27)
flutter: #8      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
flutter: <asynchronous suspension>
flutter: #9      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:27)
flutter: <asynchronous suspension>
flutter: #10     CacheManager._init (package:flutter_cache_manager/flutter_cache_manager.dart:51:38)
flutter: <asynchronous suspension>
flutter: #11     CacheManager.getInstance.<anonymous closure> (package:flutter_cache_manager/flutter_cache_manager.dart:33:29)
flutter: <asynchronous suspension>
______________________________________
Unsure why this is happening. If I run this code for my iPhone 5 in its first install it works fine.  But as soon as I do a "hot restart" or do another flutter run this error comes up again and again.   I have to delete this app from the phone for this error to go again and it's again only on the initial install, but fails on hot restart onwards.  

This does not happen on an iPhone simulator and on any live Android phones I have tested with 5.1 and 8.0.  Unfortunately I only have an iPhone 5 for live testing, so unsure how this behaves on other models.

**Comment by renefloor** [comment] 2018-10-30 13:39
@alexJetski I guess this is only a bug on 32 bit versions of iOS. It is a bug in shared_preferences. I am already working on a move to sqlite. This issue is a duplicate of #75, so I'll close it for now.

**Closed by renefloor** 2018-10-30 13:39 UTC

**Comment by alexJetski** [comment] 2018-10-31 00:00
Thanks for heads up Rene.  Looking forward to your new version with sqlite.
