### ISSUE TITLE
Because every version of flutter_test from sdk depends on http 0.12.0 

### ISSUE THREAD

**Issue by andansky** [renefloor/flutter_cached_network_image#84] opened 2018-10-12 16:23 UTC
Because every version of flutter_test from sdk depends on http 0.12.0 and flutter_cache_manager >=0.1.0-rc.1 depends on http ^0.11.3+14, flutter_test from sdk is incompatible with flutter_cache_manager >=0.1.0-rc.1.
And because cached_network_image >=0.4.1 <0.4.2 depends on flutter_cache_manager ^0.1.1, flutter_test from sdk is incompatible with cached_network_image >=0.4.1 <0.4.2.
So, because buso depends on both cached_network_image 0.4.1 and flutter_test any from sdk, version solving failed.

**Comment by renefloor** [comment] 2018-10-13 09:27
Duplicate of #81

**Closed by renefloor** 2018-10-13 09:27 UTC
