### ISSUE TITLE
application crashes when image url returns 404

### ISSUE THREAD

**Issue by m7mdra** [renefloor/flutter_cached_network_image#170] opened 2019-04-28 11:21 UTC
When i try to load an image using the library sometimes the image may not be available the application then crashes even thought i used `errorWidget` in the constructor.
here is my example:
```
 CachedNetworkImage(
                    imageUrl: userPayload.photo,
                    width: 90,
                    height: 90,
                    placeholder: (context, url) {
                      return DefaultUserAvatarWidget();
                    },
                    errorWidget: (context, url, error) {
                      return DefaultUserAvatarWidget();
                    },
                  )
```
error:  
`HttpException (HttpException: No valid statuscode. Statuscode was 404)`

**Comment by codememory101** [comment] 2019-05-07 04:06
Same happens for me.

**Comment by aerozavr** [comment] 2019-05-10 07:31
same here

**Comment by marrullas** [comment] 2019-05-11 04:49
X 4

**Comment by shpy2001** [comment] 2019-05-13 01:52
Same for me.

**Comment by ushang000** [comment] 2019-05-14 02:18
+1

**Comment by lifetin** [comment] 2019-06-25 05:23
+1

**Comment by lifetin** [comment] 2019-06-25 05:24
I/flutter ( 5552): 图片加载失败https://img.alicdn.com/imgextra/i4/2115644366/O1CN01xXfonL1i7fixv6Mw1_!!2115644366.jpg_300x300.jpg
I/flutter ( 5552): No valid statuscode. Statuscode was 404
I/flutter ( 5552): 图片加载失败https://img.alicdn.com/imgextra/i4/2115644366/O1CN01xXfonL1i7fixv6Mw1_!!2115644366.jpg_300x300.jpg
I/flutter ( 5552): No valid statuscode. Statuscode was 404
I/flutter ( 5552): onNotifySetState=>onHttpSuccess

**Comment by 229106948** [comment] 2019-07-01 07:27
same here

**Comment by jlnr** [comment] 2019-07-14 20:29
Is this a duplicate of #144 (fix in #190)?

**Comment by renefloor** [comment] 2019-07-15 06:18
Fixed

**Closed by renefloor** 2019-07-15 06:18 UTC

**Comment by charleshan** [comment] 2019-09-17 17:44
@renefloor still happening in `1.1.1`.
