### ISSUE TITLE
Slower scroll with big images

### ISSUE THREAD

**Issue by Dn-a** [renefloor/flutter_cached_network_image#90] opened 2018-11-02 14:23 UTC
In listview.builder when load big Images scrolling slows down. is there a way to resize the image?

**Comment by wwwdata** [comment] 2019-01-07 12:06
@Dn-a Does this happen for you only if using this plugin or in general? I also notice this problem but for me it is happening in general, so also when using the normal `Image.network` component from Flutter I see stuttering in my ListViews... It is a super tiny micro stutter that is noticeable maybe 2-5 frames that drop or something.

**Comment by Dn-a** [comment] 2019-01-07 12:56
I have not used other plugins so I can not tell if the problem is due to this ... the problem is highlighted a lot on old smartphones (Samsung s2 or less) with photos of size 1200px / 675px or more ... on new smartphone you they only notice micro stutter

**Comment by wwwdata** [comment] 2019-01-07 13:00
What I mean is: Maybe this is more of a flutter core issue than with this plugin. Please just try it out without this plugin and the Standard `Image.network` widget of flutter. I would be very interested in your results because this problem is driving me nuts a little bit :D

**Comment by Dn-a** [comment] 2019-01-07 13:17
certainly! I will do a test and I will let you know ... thanks for the quick reply

**Comment by zhouweidong** [comment] 2019-06-15 03:05
> In listview.builder when load big Images scrolling slows down. is there a way to resize the image?

Dear, did you solved this issues?

**Comment by renefloor** [comment] 2019-08-14 16:20
I assume this as duplicate of #63

**Closed by renefloor** 2019-08-14 16:20 UTC
