### ISSUE TITLE
Please provide a way for developer to handle the error when failed to load image

### ISSUE THREAD

**Issue by dansuse** [renefloor/flutter_cached_network_image#80] opened 2018-10-03 08:07 UTC
This is the stack trace, Thank you for developing this library

`══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (21260): The following _Exception was thrown resolving an image codec:
I/flutter (21260): Exception: Couldn't download or retreive file.
I/flutter (21260): 
I/flutter (21260): When the exception was thrown, this was the stack:
I/flutter (21260): #0      CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:475:7)
I/flutter (21260): <asynchronous suspension>
I/flutter (21260): #1      CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:462:16)
I/flutter (21260): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
I/flutter (21260): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
I/flutter (21260): #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
I/flutter (21260): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (21260): #6      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:30)
I/flutter (21260): #7      _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:193:29)
I/flutter (21260): #8      _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:284:20)
I/flutter (21260): #9      _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:261:5)
I/flutter (21260): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3779:12)
I/flutter (21260): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #18     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
I/flutter (21260): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
I/flutter (21260): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (21260): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #51     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (21260): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (21260): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (21260): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #90     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #99     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #104    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #114    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (21260): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #127    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
I/flutter (21260): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (21260): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (21260): #132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (21260): #133    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (21260): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (21260): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (21260): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (21260): #137    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
I/flutter (21260): #138    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:20)
I/flutter (21260): #139    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/zygote  (21260): Do full code cache collection, code=122KB, data=87KB
I/zygote  (21260): After code cache collection, code=105KB, data=62KB
I/flutter (21260): #140    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
I/flutter (21260): #141    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter (21260): #142    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1727:58)
I/flutter (21260): #143    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter (21260): #144    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1727:13)
I/flutter (21260): #145    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter (21260): #146    RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
I/flutter (21260): #147    RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:543:12)
I/flutter (21260): #148    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (21260): #149    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (21260): #150    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
I/flutter (21260): #151    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
I/flutter (21260): #152    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
I/flutter (21260): #153    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (21260): #154    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (21260): #155    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (21260): #156    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (21260): #157    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (21260): #158    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (21260): #159    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (21260): #160    _invoke (dart:ui/hooks.dart:128:13)
I/flutter (21260): #161    _drawFrame (dart:ui/hooks.dart:117:3)`

**Comment by renefloor** [comment] 2018-10-20 11:09
I see this as a duplicate of #71, the library should provide better feedback in general.

**Closed by renefloor** 2018-10-20 11:09 UTC
