### ISSUE TITLE
Maximum size?

### ISSUE THREAD

**Issue by jonahgreenthal** [renefloor/flutter_cached_network_image#74] opened 2018-08-30 21:35 UTC
I'm trying to load some large PNG images (11238x9868, 716 KB; 5950x7242, 228 KB; 10565x6160, 409 KB; 7750x8180, 463 KB) and nothing happens—eventually the loading indicator stops and I'm left with a blank white box. Smaller images (I'm using a 362x164, 11 KB image for small testing) work fine. This is in the Android Studio emulator, in case that matters.

Are there known limits on size? Any tips for making large images work?

(In case you have any suggestions, I'll note that what I really want to do is display a vector image. Pretty much any vector format would be fine. But I can't seem to find any solution that will work on both iOS and Android. I'm using a high-resolution PNG as a substitute. My other best current idea is to load a PDF in a webview using [`flutter_webview_plugin`](https://github.com/dart-flitter/flutter_webview_plugin), which isn't a great solution.)

**Comment by renefloor** [comment] 2018-09-14 08:49
Not sure. I wouldn't expect a limitation on size.

**Comment by zhouweidong** [comment] 2019-06-15 03:08
> I'm trying to load some large PNG images (11238x9868, 716 KB; 5950x7242, 228 KB; 10565x6160, 409 KB; 7750x8180, 463 KB) and nothing happens—eventually the loading indicator stops and I'm left with a blank white box. Smaller images (I'm using a 362x164, 11 KB image for small testing) work fine. This is in the Android Studio emulator, in case that matters.
> 
> Are there known limits on size? Any tips for making large images work?
> 
> (In case you have any suggestions, I'll note that what I really want to do is display a vector image. Pretty much any vector format would be fine. But I can't seem to find any solution that will work on both iOS and Android. I'm using a high-resolution PNG as a substitute. My other best current idea is to load a PDF in a webview using [`flutter_webview_plugin`](https://github.com/dart-flitter/flutter_webview_plugin), which isn't a great solution.)

dear do you solved this issues?

**Comment by jonahgreenthal** [comment] 2019-06-15 13:07
No. I went with the PDF+webview solution.

**Comment by renefloor** [comment] 2019-08-14 16:20
I assume this as duplicate of #63

**Closed by renefloor** 2019-08-14 16:20 UTC

**Comment by jonahgreenthal** [comment] 2019-08-14 18:07
I don't see how this is a duplicate of #63. Please reopen.
