### ISSUE TITLE
Fit issues with Flutter 1.2

### ISSUE THREAD

**Issue by jesusrp98** [renefloor/flutter_cached_network_image#135] opened 2019-02-28 11:37 UTC
Since I updated to Flutter 1.2 a couple days ago, the `fit` parameter doesn't work properly. It doesn't cover its parent.

Here is the widget:
```
return CachedNetworkImage(
  imageUrl: url,
  errorWidget: (context, url, error) => Icon(
        Icons.cancel,
        size: 32,
        color: Theme.of(context).textTheme.caption.color,
      ),
  fadeInDuration: Duration(milliseconds: 100),
  fit: BoxFit.cover,
);
```
And here is the final result, using a simple `ListTile` widget, in Debug Painting mode.
As you can see, there's empty space between the `CachedNetworkImage` and its parent, even though the `fit` parameter is set to cover.

![screenshot from 2019-02-28 12-31-10](https://user-images.githubusercontent.com/8961959/53563591-c894d700-3b54-11e9-933b-cf46596ee358.png)

**Comment by renefloor** [comment] 2019-02-28 13:22
Currently you need to set height and or width, for example to double.INFINITY. Duplicate of #134.

**Closed by renefloor** 2019-02-28 13:22 UTC
