### ISSUE TITLE
CachedNetworkImageProvider.load error

### ISSUE THREAD

**Issue by bruceyue** [renefloor/flutter_cached_network_image#268] opened 2019-10-17 09:49 UTC
The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
 
ImageStreamCompleter load(CachedNetworkImageProvider key)
From flutter source, there is two params
ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by renefloor** [comment] 2019-10-17 09:51
Please have a look at other issues before posting one.
Duplicate of #266 en #261

**Closed by renefloor** 2019-10-17 09:51 UTC

**Comment by maAsh-yuppee** [comment] 2019-12-10 11:21
Just replace cached_network_image: ^1.1.3 to  cached_network_image: ^2.0.0-rc.1
https://pub.dev/packages/cached_network_image/versions/2.0.0-rc.1#-installing-tab-
