### ISSUE TITLE
fit: Boxfit not working as expected (not working unless height/width is set)

### ISSUE THREAD

**Issue by abinmittu** [renefloor/flutter_cached_network_image#134] opened 2019-02-27 06:23 UTC
fit: Boxfit.cover not working for image in lastest update

**Comment by renefloor** [comment] 2019-02-27 11:21
It should work if you set height and/or width. Otherwise it just takes the size it needs for the image. If you set height and width to double.INFINITY it should work as previously. I'll update the documentation for that. If it doesn't please re-open this issue.

**Comment by renefloor** [comment] 2019-02-28 13:21
I'll reopen this, as it is no expected behaviour.

**Comment by jesusrp98** [comment] 2019-02-28 14:52
So, setting the height and width to double.INFINITY is the final solution, or is this going to be fixed?

**Comment by renefloor** [comment] 2019-03-06 20:42
Fixed in 0.7.0

**Closed by renefloor** 2019-03-06 20:42 UTC

**Comment by dixonary** [comment] 2019-08-05 19:47
Using latest, same behaviour seems to be present.

**Comment by erperejildo** [comment] 2020-02-19 12:55
still present in 1.12 but fixed with @jesusrp98 suggestion

**Comment by AERODARIUS** [comment] 2020-03-15 02:36
Using `DecorationImage` I could make it work:
```
class Default extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        image: DecorationImage(
            image: AssetImage('../image.jpg'),
            fit: BoxFit.cover),
      ),
    );
  }
}
```

**Comment by Zony-Zhao** [comment] 2020-10-31 02:40
still present in 1.20 but fixed with @renefloor suggestion

**Comment by tony123S** [comment] 2020-11-26 11:03
not working...

```
Widget _showImages(var item) {
    return SizedBox(
        height: 150,
        width: double.infinity,
        child: ListView.builder(
            shrinkWrap: true,
            scrollDirection: Axis.horizontal,
            itemCount: item['part_2_attachments'].length,
            itemBuilder: (context, index) {
              var i = item['part_2_attachments'][index];

              return InkWell(
                  onTap: () {
                      ....
                  },
                  child: Container(
                      height: 150,
                      width: 150,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                            image: NetworkImage("https://...",
                            fit: BoxFit.cover),
                      )));
            }));
  }
```

There still has space...

**Comment by tiklup11** [comment] 2022-07-11 10:48
still present in 3.2.0 &  changing width to double.infinity doesn't seems to work.

**Comment by arvicxyz** [comment] 2023-05-17 05:11
Still getting this issue in 2023 Flutter 3.10. The problem I think is the image is not stretching to overlap with the other images in my grid. Note, all data are static in my sample app and in the screenshot you can see the red boxdecoration color showing on smaller images but for the larger image it doesn't show. Also if I change the image to the swimming image for all it does cover the whole container.

![image](https://github.com/Baseflow/flutter_cached_network_image/assets/12872945/1aa55bfa-2d94-49a4-9dfb-a24c7a632b1b)

`child: Stack(
              children: [
                Hero(
                  tag: WorkoutsService().getAllWorkoutSetNames()[index],
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.red,
                      image: DecorationImage(
                        image: AssetImage("assets/images/${WorkoutsService().getAllWorkoutImgList()[index]}.png"),
                        fit: BoxFit.cover,
                      ),
                      borderRadius: BorderRadius.circular(kWorkoutCardBorderRadius),
                    ),
                  ),
                ),`
